### ISSUE TITLE
Link issue

### ISSUE THREAD

**Issue by FREDVUNI** [ZainRk/Full-stack-real-estate-youtube#1]
The link URL is broken

**Comment by ankit705yadav** [comment]
which link are you talking of?

**Comment by FREDVUNI** [comment]
https://full-stack-real-estate-youtube.vercel.app/

> which link are you talking of?

**Comment by deepak-ks-sde** [comment]
sir actually authentication error with the jwt check server not posting the
user to the backend and Oauth is not free

**Comment by ankit705yadav** [comment]
> 

https://full-stack-real-estate-youtube-sooty.vercel.app/
